// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5658ebb7-8158-4412-bb27-b87975f15829"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 1, 13, 21, 47, 1, 500, DateTimeKind.Utc).AddTicks(8836),
                            Description = "Activity 2 months ago",
                            Title = "Past Activity 1",
                            Venue = "Pub"
                        },
                        new
                        {
                            Id = new Guid("80c0c095-1b93-4386-aa2f-d8a060404a46"),
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2024, 2, 13, 21, 47, 1, 500, DateTimeKind.Utc).AddTicks(8845),
                            Description = "Activity 1 month ago",
                            Title = "Past Activity 2",
                            Venue = "Louvre"
                        },
                        new
                        {
                            Id = new Guid("6f821604-6c92-4ee3-b40b-00be398d9d2b"),
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2024, 4, 13, 21, 47, 1, 500, DateTimeKind.Utc).AddTicks(8848),
                            Description = "Activity 1 month in future",
                            Title = "Future Activity 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            Id = new Guid("d9cf3989-3a25-4092-910a-5a259f0aac7d"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2024, 5, 13, 21, 47, 1, 500, DateTimeKind.Utc).AddTicks(8850),
                            Description = "Activity 2 months in future",
                            Title = "Future Activity 2",
                            Venue = "O2 Arena"
                        },
                        new
                        {
                            Id = new Guid("f779069d-f6fc-426c-ba06-21171568f032"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 6, 13, 21, 47, 1, 500, DateTimeKind.Utc).AddTicks(8852),
                            Description = "Activity 3 months in future",
                            Title = "Future Activity 3",
                            Venue = "Another pub"
                        },
                        new
                        {
                            Id = new Guid("d7f97a06-b8b5-4947-a46c-46ee8d793983"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 7, 13, 21, 47, 1, 500, DateTimeKind.Utc).AddTicks(8863),
                            Description = "Activity 4 months in future",
                            Title = "Future Activity 4",
                            Venue = "Yet another pub"
                        },
                        new
                        {
                            Id = new Guid("d33aa8e4-34ae-41c4-a0c6-4465bb95ca4a"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 8, 13, 21, 47, 1, 500, DateTimeKind.Utc).AddTicks(8866),
                            Description = "Activity 5 months in future",
                            Title = "Future Activity 5",
                            Venue = "Just another pub"
                        },
                        new
                        {
                            Id = new Guid("7945e681-5bd7-43f4-8330-9a00cc8b30e3"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2024, 9, 13, 21, 47, 1, 500, DateTimeKind.Utc).AddTicks(8867),
                            Description = "Activity 6 months in future",
                            Title = "Future Activity 6",
                            Venue = "Roundhouse Camden"
                        },
                        new
                        {
                            Id = new Guid("a7c058ad-e2a2-4a28-8802-8478277be897"),
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2024, 10, 13, 21, 47, 1, 500, DateTimeKind.Utc).AddTicks(8869),
                            Description = "Activity 2 months ago",
                            Title = "Future Activity 7",
                            Venue = "Somewhere on the Thames"
                        },
                        new
                        {
                            Id = new Guid("02c830b3-19d6-4548-87ec-ad28817fc27b"),
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2024, 11, 13, 21, 47, 1, 500, DateTimeKind.Utc).AddTicks(8871),
                            Description = "Activity 8 months in future",
                            Title = "Future Activity 8",
                            Venue = "Cinema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
