// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a73ce9ba-beb9-4013-9056-1f3f283a8878"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 4, 13, 23, 20, 54, 924, DateTimeKind.Utc).AddTicks(9145),
                            Description = "Activity 2 months ago",
                            Title = "Past Activity 1",
                            Venue = "Pub"
                        },
                        new
                        {
                            Id = new Guid("fb6ce523-c7e2-4b4c-8dab-0557863805c3"),
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2024, 5, 13, 23, 20, 54, 924, DateTimeKind.Utc).AddTicks(9159),
                            Description = "Activity 1 month ago",
                            Title = "Past Activity 2",
                            Venue = "Louvre"
                        },
                        new
                        {
                            Id = new Guid("fc72132a-80c7-4578-9bff-a515d7b78c57"),
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2024, 7, 13, 23, 20, 54, 924, DateTimeKind.Utc).AddTicks(9164),
                            Description = "Activity 1 month in future",
                            Title = "Future Activity 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            Id = new Guid("add9c315-b081-46e8-97a5-422a19144fc7"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2024, 8, 13, 23, 20, 54, 924, DateTimeKind.Utc).AddTicks(9168),
                            Description = "Activity 2 months in future",
                            Title = "Future Activity 2",
                            Venue = "O2 Arena"
                        },
                        new
                        {
                            Id = new Guid("5e2dca1b-591f-4834-9e7a-df1c640becd7"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 9, 13, 23, 20, 54, 924, DateTimeKind.Utc).AddTicks(9172),
                            Description = "Activity 3 months in future",
                            Title = "Future Activity 3",
                            Venue = "Another pub"
                        },
                        new
                        {
                            Id = new Guid("2f26c54b-c7b9-45be-ad35-f7ae87eac107"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 10, 13, 23, 20, 54, 924, DateTimeKind.Utc).AddTicks(9175),
                            Description = "Activity 4 months in future",
                            Title = "Future Activity 4",
                            Venue = "Yet another pub"
                        },
                        new
                        {
                            Id = new Guid("a7300a49-c328-4af7-b5b7-6f57c283f809"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 11, 13, 23, 20, 54, 924, DateTimeKind.Utc).AddTicks(9179),
                            Description = "Activity 5 months in future",
                            Title = "Future Activity 5",
                            Venue = "Just another pub"
                        },
                        new
                        {
                            Id = new Guid("bc531442-2603-4171-b814-de35a511407b"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2024, 12, 13, 23, 20, 54, 924, DateTimeKind.Utc).AddTicks(9202),
                            Description = "Activity 6 months in future",
                            Title = "Future Activity 6",
                            Venue = "Roundhouse Camden"
                        },
                        new
                        {
                            Id = new Guid("11ba1e85-67a1-4afd-a9a9-58fbe8e05988"),
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2025, 1, 13, 23, 20, 54, 924, DateTimeKind.Utc).AddTicks(9206),
                            Description = "Activity 2 months ago",
                            Title = "Future Activity 7",
                            Venue = "Somewhere on the Thames"
                        },
                        new
                        {
                            Id = new Guid("a42f92f6-373c-4575-9575-c8868d4ef733"),
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2025, 2, 13, 23, 20, 54, 924, DateTimeKind.Utc).AddTicks(9210),
                            Description = "Activity 8 months in future",
                            Title = "Future Activity 8",
                            Venue = "Cinema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
